# Generated by Django 2.2.6 on 2019-10-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Your full name')),
                ('address', models.TextField(blank=True, verbose_name='Your address')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Your email')),
                ('turnover_tax_number', models.CharField(blank=True, max_length=255, verbose_name='You turnover tax number')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Bank name')),
                ('iban', models.CharField(blank=True, max_length=255, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=255, verbose_name='BIC')),
                ('currency', models.CharField(default='€', max_length=10, verbose_name='Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
