[project]
name = "documentpanda"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "django==6.0.4",
    "django-extensions==4.1",
    "django-solo==2.5.1",
    "pytz==2026.1.post1",
    "reportlab==4.5.1",
]

[dependency-groups]
dev = [
    "pre-commit==4.6.0",
    "pytest==9.0.3",
    "pytest-django==4.12.0",
    "pytest-sugar==1.1.1",
    "ruff==0.15.12",
]
