# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Customer name')),
                ('customer_id', models.IntegerField(unique=True, verbose_name='Customer ID')),
                ('default_fee', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Project fee per hour')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['customer_id'],
            },
        ),
    ]
