# Generated by Django 2.2.6 on 2019-11-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_add_invoice_address_to_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='invoice_address',
        ),
        migrations.AddField(
            model_name='customer',
            name='contract_number',
            field=models.CharField(blank=True, max_length=128, verbose_name='Contract number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Invoice city of the customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Invoice name of the customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Invoice street of the customer'),
        ),
    ]
