# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.PositiveSmallIntegerField(verbose_name='Customer ID')),
                ('name', models.CharField(max_length=255, verbose_name='Customer name')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Project fee')),
                ('start', models.DateField(verbose_name='Project start')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Project end')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
        ),
    ]
