# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp_customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fee',
            new_name='default_fee',
        ),
    ]
