# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp_customer', '0003_auto_20170409_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customer_id']},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='end',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='start',
        ),
    ]
