# Generated by Django 3.0.9 on 2020-08-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20190928_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthreport',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=4, verbose_name='VAT in %'),
        ),
        migrations.AlterField(
            model_name='monthreport',
            name='year',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], verbose_name='Year'),
        ),
    ]
