# Generated by Django 3.1.2 on 2020-10-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20200805_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthreport',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Fixed price'),
        ),
        migrations.AlterField(
            model_name='monthreport',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Project fee per hour'),
        ),
        migrations.AlterField(
            model_name='monthreport',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Working hours'),
        ),
    ]
