# Generated by Django 2.2.5 on 2019-09-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_introduce_tax_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['-year']},
        ),
        migrations.AddField(
            model_name='tax',
            name='taxable_income',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Taxable Income'),
            preserve_default=False,
        ),
    ]
