# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dp_customer', '0004_auto_20170618_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Project fee')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=6, verbose_name='Month')),
                ('year', models.IntegerField(choices=[(2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017, verbose_name='Year')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Working hours')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='month', to='dp_customer.Customer', verbose_name='Customer')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='monthreport',
            unique_together=set([('customer', 'month', 'year')]),
        ),
    ]
