# Generated by Django 2.2.6 on 2019-10-22 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0006_auto_20190928_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=32, unique=True)),
                ('your_full_name', models.CharField(max_length=255)),
                ('your_address', models.TextField()),
                ('customer_address', models.TextField()),
                ('invoice_date', models.DateField()),
                ('invoice_period_begin', models.DateField()),
                ('invoice_period_end', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('turnover_tax_number', models.CharField(max_length=32)),
                ('bank_name', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=255)),
                ('bic', models.CharField(max_length=255)),
                ('month_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.MonthReport', verbose_name='Month report')),
            ],
        ),
    ]
