# Generated by Django 2.2.6 on 2019-11-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_introduce_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='file_path',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
